### ISSUE TITLE
タイムアウト設定時間が短い

### ISSUE THREAD

**Issue by tk1024** [you21979/node-zaif#7]
`OPT_TIMEOUT_SEC`が5msになっていますが、さすがに5msは短すぎるのでは無いかと思います。

**Comment by you21979** [comment]
タイムアウトはデフォルトで5秒です

timeout: Math.floor(constant.OPT_TIMEOUT_SEC * 1000)

**Comment by tk1024** [comment]
あ、本当だ...
`trade_history`のレスポンスが5秒以内に返ってくる事がなかったので勘違いしてました。
すみません、ありがとうございます。
