### ISSUE TITLE
forkしても大丈夫でしょうか？

### ISSUE THREAD

**Issue by RossyWhite** [you21979/node-zaif#9]
お世話になります。

先日先物取引のAPIをリリースしまして、
これを機に、各言語のAPIラッパーを[テックビューロのアカウント](https://github.com/techbureau)に集めようとしているのですが、
差し支えなければ、このリポジトリを使用させていただいてもよろしいでしょうか？

**Comment by you21979** [comment]
MITライセンスで公開しているのでフォーク自体は勝手にして問題ないです。
